# Generated by Django 5.2.7 on 2025-10-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requete',
            name='etat',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('arriver', 'Arrivé'), ('confirme', 'Confirmé')], default='en_attente', max_length=20),
        ),
    ]
