# Generated by Django 5.2.7 on 2025-10-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_requete_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requete',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
